### ISSUE TITLE
[Feature Flag Cleanup] Cleanup code to remove dark mode feature flag

### ISSUE THREAD

**Issue by kageiit** [gitarcode/feature-flags-demo#68]
We've decided to fully roll out the is-dark-mode-enabled feature flag. We now need to optimize our code by removing all checks for this feature flag, and simplify logic.

**Comment by nid90** [comment]
@gitar-bot cleanup is-dark-mode-enabled=true

**Comment by aadltaba** [comment]
@gitar-bot cleanup is-dark-mode-enabled=true

**Comment by aadltaba** [comment]
@gitar-bot cleanup is-dark-mode-enabled=true

**Comment by aadltaba** [comment]
@gitar-bot cleanup is-dark-mode-enabled=true

**Comment by aadltaba** [comment]
@gitar-bot cleanup is-dark-mode-enabled=true

**Comment by aadltaba** [comment]
@gitar-bot cleanup is-dark-mode-enabled=true

**Comment by alexanderles** [comment]
@gitar-bot cleanup is-dark-mode-enabled=true

**Comment by naveenOnarayanan** [comment]
@gitar-bot cleanup is-dark-mode-enabled=true

**Comment by naveenOnarayanan** [comment]
@gitar-bot cleanup is-dark-mode-enabled=true

**Comment by rajbarik** [comment]
@gitar-bot cleanup is-dark-mode-enabled=true

**Comment by Kakapio** [comment]
@gitar-bot cleanup is-dark-mode-enabled=true
