### ISSUE TITLE
[Feature Flag Cleanup] Cleanup code to remove dark mode feature flag

### ISSUE THREAD

**Issue by kageiit** [gitarcode/feature-flags-demo#83]

**Comment by kageiit** [comment]
@gitar-bot cleanup is-dark-mode-enabled=true

**Comment by naveenOnarayanan** [comment]
@gitar-bot cleanup is-dark-mode-enabled=true

**Comment by alexanderles** [comment]
@gitar-bot cleanup is-dark-mode-enabled=true

**Comment by aadltaba** [comment]
staging @gitar-bot cleanup is-dark-mode-enabled=true

**Comment by aadltaba** [comment]
@gitar-bot cleanup is-dark-mode-enabled=true

**Comment by kageiit** [comment]
@gitar-bot cleanup is-dark-mode-enabled=true

**Comment by aadltaba** [comment]
@gitar-bot cleanup is-dark-mode-enabled=true

**Comment by lazaroclapp** [comment]
@gitar-bot cleanup is-dark-mode-enabled=true
